# EXPERIMENT 19 and 20
#Covid Data Analysis
#Divisha Ingavale
#PRN: 25070123043
#ENTC A2

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/covid_19_data.csv")
data.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [ ]:
data=data.drop(['SNo','Last Update'],axis=1)
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  306429 non-null  object
 1   Province/State   228326 non-null  object
 2   Country/Region   306429 non-null  object
 3   Confirmed        306429 non-null  float64
 4   Deaths           306429 non-null  float64
 5   Recovered        306429 non-null  float64
dtypes: float64(3), object(3)
memory usage: 14.0+ MB

In [ ]:
data['ObservationDate']= data['ObservationDate'].astype('datetime64[ns]')
data['Confirmed']= data['Confirmed'].astype('int64')
data['Deaths']= data['Deaths'].astype('int64')
data['Recovered']= data['Recovered'].astype('int64')
data

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered
0,2020-01-22,Anhui,Mainland China,1,0,0
1,2020-01-22,Beijing,Mainland China,14,0,0
2,2020-01-22,Chongqing,Mainland China,6,0,0
3,2020-01-22,Fujian,Mainland China,1,0,0
4,2020-01-22,Gansu,Mainland China,0,0,0
...,...,...,...,...,...,...
306424,2021-05-29,Zaporizhia Oblast,Ukraine,102641,2335,95289
306425,2021-05-29,Zeeland,Netherlands,29147,245,0
306426,2021-05-29,Zhejiang,Mainland China,1364,1,1324
306427,2021-05-29,Zhytomyr Oblast,Ukraine,87550,1738,83790
306428,2021-05-29,Zuid-Holland,Netherlands,391559,4252,0

In [ ]:
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      2020-01-22          Anhui  Mainland China          1       0          0
1      2020-01-22        Beijing  Mainland China         14       0          0
2      2020-01-22      Chongqing  Mainland China          6       0          0
3      2020-01-22         Fujian  Mainland China          1       0          0
4      2020-01-22          Gansu  Mainland China          0       0          0

In [ ]:
###Active case
#Can use this function with the use of pandas
data['Active']=data['Confirmed']-(data['Deaths']+data['Recovered'])
data.head(50)

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
0,2020-01-22,Anhui,Mainland China,1,0,0,1
1,2020-01-22,Beijing,Mainland China,14,0,0,14
2,2020-01-22,Chongqing,Mainland China,6,0,0,6
3,2020-01-22,Fujian,Mainland China,1,0,0,1
4,2020-01-22,Gansu,Mainland China,0,0,0,0
5,2020-01-22,Guangdong,Mainland China,26,0,0,26
6,2020-01-22,Guangxi,Mainland China,2,0,0,2
7,2020-01-22,Guizhou,Mainland China,1,0,0,1
8,2020-01-22,Hainan,Mainland China,4,0,0,4
9,2020-01-22,Hebei,Mainland China,1,0,0,1
10,2020-01-22,Heilongjiang,Mainland China,0,0,0,0
11,2020-01-22,Henan,Mainland China,5,0,0,5
12,2020-01-22,Hong Kong,Hong Kong,0,0,0,0
13,2020-01-22,Hubei,Mainland China,444,17,28,399
14,2020-01-22,Hunan,Mainland China,4,0,0,4
15,2020-01-22,Inner Mongolia,Mainland China,0,0,0,0
16,2020-01-22,Jiangsu,Mainland China,1,0,0,1
17,2020-01-22,Jiangxi,Mainland China,2,0,0,2
18,2020-01-22,Jilin,Mainland China,0,0,0,0
19,2020-01-22,Liaoning,Mainland China,2,0,0,2
20,2020-01-22,Macau,Macau,1,0,0,1
21,2020-01-22,Ningxia,Mainland China,1,0,0,1
22,2020-01-22,Qinghai,Mainland China,0,0,0,0
23,2020-01-22,Shaanxi,Mainland China,0,0,0,0
24,2020-01-22,Shandong,Mainland China,2,0,0,2
25,2020-01-22,Shanghai,Mainland China,9,0,0,9
26,2020-01-22,Shanxi,Mainland China,1,0,0,1
27,2020-01-22,Sichuan,Mainland China,5,0,0,5
28,2020-01-22,Taiwan,Taiwan,1,0,0,1
29,2020-01-22,Tianjin,Mainland China,4,0,0,4
30,2020-01-22,Tibet,Mainland China,0,0,0,0
31,2020-01-22,Washington,US,1,0,0,1
32,2020-01-22,Xinjiang,Mainland China,0,0,0,0
33,2020-01-22,Yunnan,Mainland China,1,0,0,1
34,2020-01-22,Zhejiang,Mainland China,10,0,0,10
35,2020-01-22,NaN,Japan,2,0,0,2
36,2020-01-22,NaN,Thailand,4,0,2,2
37,2020-01-22,NaN,South Korea,1,0,0,1
38,2020-01-22,Unknown,China,0,0,0,0
39,2020-01-22,NaN,Kiribati,0,0,0,0
40,2020-01-23,Anhui,Mainland China,9,0,0,9
41,2020-01-23,Beijing,Mainland China,22,0,0,22
42,2020-01-23,Chongqing,Mainland China,9,0,0,9
43,2020-01-23,Fujian,Mainland China,5,0,0,5
44,2020-01-23,Gansu,Mainland China,2,0,0,2
45,2020-01-23,Guangdong,Mainland China,32,0,2,30
46,2020-01-23,Guangxi,Mainland China,5,0,0,5
47,2020-01-23,Guizhou,Mainland China,3,0,0,3
48,2020-01-23,Hainan,Mainland China,5,0,0,5
49,2020-01-23,Hubei,Mainland China,444,17,28,399

In [ ]:
#iloc( intermidiate data {from where to where})
data.iloc[50:100] #specifies range from where data is to be obtained from

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
50,2020-01-23,Heilongjiang,Mainland China,2,0,0,2
51,2020-01-23,Henan,Mainland China,5,0,0,5
52,2020-01-23,Hong Kong,Hong Kong,2,0,0,2
53,2020-01-23,Hubei,Mainland China,444,17,28,399
54,2020-01-23,Hunan,Mainland China,9,0,0,9
55,2020-01-23,Inner Mongolia,Mainland China,0,0,0,0
56,2020-01-23,Jiangsu,Mainland China,5,0,0,5
57,2020-01-23,Jiangxi,Mainland China,7,0,0,7
58,2020-01-23,Jilin,Mainland China,1,0,0,1
59,2020-01-23,Liaoning,Mainland China,3,0,0,3
60,2020-01-23,Macau,Macau,2,0,0,2
61,2020-01-23,Ningxia,Mainland China,1,0,0,1
62,2020-01-23,Qinghai,Mainland China,0,0,0,0
63,2020-01-23,Shaanxi,Mainland China,3,0,0,3
64,2020-01-23,Shandong,Mainland China,6,0,0,6
65,2020-01-23,Shanghai,Mainland China,16,0,0,16
66,2020-01-23,Shanxi,Mainland China,1,0,0,1
67,2020-01-23,Sichuan,Mainland China,8,0,0,8
68,2020-01-23,Taiwan,Taiwan,1,0,0,1
69,2020-01-23,Tianjin,Mainland China,4,0,0,4
70,2020-01-23,Tibet,Mainland China,0,0,0,0
71,2020-01-23,Washington,US,1,0,0,1
72,2020-01-23,Xinjiang,Mainland China,2,0,0,2
73,2020-01-23,Yunnan,Mainland China,2,0,0,2
74,2020-01-23,Zhejiang,Mainland China,27,0,0,27
75,2020-01-23,NaN,Japan,1,0,0,1
76,2020-01-23,NaN,Thailand,4,0,2,2
77,2020-01-23,NaN,South Korea,1,0,0,1
78,2020-01-23,NaN,Singapore,1,0,0,1
79,2020-01-23,NaN,Philippines,0,0,0,0
80,2020-01-23,NaN,Malaysia,0,0,0,0
81,2020-01-23,NaN,Vietnam,2,0,0,2
82,2020-01-23,NaN,Australia,0,0,0,0
83,2020-01-23,NaN,Mexico,0,0,0,0
84,2020-01-23,NaN,Brazil,0,0,0,0
85,2020-01-23,NaN,Colombia,0,0,0,0
86,2020-01-23,Unknown,China,0,0,0,0
87,2020-01-23,NaN,Kiribati,0,0,0,0
88,2020-01-24,Hubei,Mainland China,549,24,31,494
89,2020-01-24,Guangdong,Mainland China,53,0,2,51
90,2020-01-24,Zhejiang,Mainland China,43,0,1,42
91,2020-01-24,Beijing,Mainland China,36,0,1,35
92,2020-01-24,Chongqing,Mainland China,27,0,0,27
93,2020-01-24,Hunan,Mainland China,24,0,0,24
94,2020-01-24,Guangxi,Mainland China,23,0,0,23
95,2020-01-24,Shanghai,Mainland China,20,0,1,19
96,2020-01-24,Jiangxi,Mainland China,18,0,0,18
97,2020-01-24,Sichuan,Mainland China,15,0,0,15
98,2020-01-24,Shandong,Mainland China,15,0,0,15
99,2020-01-24,Anhui,Mainland China,15,0,0,15

In [ ]:
###last/current data

data['ObservationDate'].max()

Timestamp('2021-05-29 00:00:00')

In [ ]:
### Fetch the latest data
latest_data=data['ObservationDate']== data['ObservationDate'].max
latest_data.head()

0    False
1    False
2    False
3    False
4    False
Name: ObservationDate, dtype: bool

In [ ]:
latest_data.shape

(306429,)

In [ ]:
latest_date = data['ObservationDate'].max()
latest_data = data[data['ObservationDate'] == latest_date]
latest_data['Country/Region'].value_counts()

Country/Region
Russia                83
US                    58
Japan                 49
India                 37
Colombia              34
                      ..
Venezuela              1
Vietnam                1
West Bank and Gaza     1
Hong Kong              1
Macau                  1
Name: count, Length: 195, dtype: int64

In [ ]:
latest_data['Country/Region'].nunique()

195

In [ ]:
latest_data['Country/Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Diamond Princess',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See',
       'Honduras', 'Hungary', 'Iceland', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Ivory Coast', 'Jamaica', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'MS Zaandam',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Micronesia',
       'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Namibia', 'Nepal', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Korea', 'South Sudan', 'Sri Lanka', 'Sudan', 'Suriname',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Uganda', 'United Arab Emirates', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'West Bank and Gaza', 'Yemen', 'Zambia', 'Zimbabwe', 'Italy',
       'Brazil', 'Russia', 'Mexico', 'Japan', 'US', 'Canada', 'Colombia',
       'Peru', 'Spain', 'India', 'UK', 'Mainland China', 'Chile',
       'Belgium', 'Netherlands', 'Australia', 'Pakistan', 'Germany',
       'Sweden', 'Ukraine', 'Hong Kong', 'Macau'], dtype=object)

In [ ]:
##Count of cases for each country
countries = latest_data.groupby("Country/Region")[["Confirmed","Deaths","Recovered","Active"]].sum()
countries = countries.reset_index()
countries

         Country/Region  Confirmed  Deaths  Recovered  Active
0           Afghanistan      70111    2899      57281    9931
1               Albania     132297    2449     129215     633
2               Algeria     128456    3460      89419   35577
3               Andorra      13693     127      13416     150
4                Angola      34180     757      27646    5777
..                  ...        ...     ...        ...     ...
190             Vietnam       6908      47       2896    3965
191  West Bank and Gaza     307838    3492     300524    3822
192               Yemen       6731    1319       3399    2013
193              Zambia      94751    1276      91594    1881
194            Zimbabwe      38933    1594      36578     761

[195 rows x 5 columns]

In [ ]:
countries[countries['Country/Region'] == 'Mainland China']

     Country/Region  Confirmed  Deaths  Recovered  Active
107  Mainland China      91072    4636      86117     319

In [ ]:
countries[countries['Country/Region'] == 'India']

   Country/Region  Confirmed  Deaths  Recovered   Active
78          India   27894800  325972   25454320  2114508

In [ ]:
countries[countries['Country/Region'] == 'US']

    Country/Region  Confirmed  Deaths  Recovered    Active
182             US   33251939  594306          0  32657633

In [ ]:
## Plot of world map
import plotly.express as px

world_map = px.choropleth(countries,locations="Country/Region",locationmode="country names",
                          color= "Confirmed", color_continuous_scale="greens", range_color=[0,1000000])
world_map

In [ ]:
import plotly.express as px

world_map = px.choropleth(countries,locations="Country/Region",locationmode="country names",
                          color= "Confirmed", color_continuous_scale="blues", range_color=[0,1000000])
world_map

In [ ]:
###Top 20 countries having maximum confirmed and recovered cases

top = latest_data.groupby("Country/Region")[['Confirmed','Recovered']].sum().reset_index()
top=top.sort_values(['Confirmed'],ascending=False)
top.head()

    Country/Region  Confirmed  Recovered
182             US   33251939          0
78           India   27894800   25454320
23          Brazil   16471600   14496224
60          France    5719877     390878
180         Turkey    5235978    5094279

In [ ]:
top_20 =top.head(20)
top_20

     Country/Region  Confirmed  Recovered
182              US   33251939          0
78            India   27894800   25454320
23           Brazil   16471600   14496224
60           France    5719877     390878
180          Turkey    5235978    5094279
144          Russia    4995613    4616422
181              UK    4496823      15481
84            Italy    4213055    3845087
6         Argentina    3732263    3288467
64          Germany    3684672    3479700
165           Spain    3668658     150376
36         Colombia    3363061    3141549
80             Iran    2893218    2425033
140          Poland    2871371    2636675
116          Mexico    2411503    1924865
184         Ukraine    2257904    2084477
138            Peru    1947555    1897522
79        Indonesia    1809926    1659974
126     Netherlands    1671967      26810
44   Czech Republic    1660935    1617498